version: '3.8'

services:
  frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      VITE_BACKEND_URL: http://localhost:8080/api
    depends_on:
      - backend

  nginx:
    image: nginx:1.25-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: reverse-proxy
    depends_on:
      - frontend

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  redis:
    image: redis
    ports:
      - 6379:6379

  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/the_database?authSource=admin
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis